package:
  name: decimate
  version: "0.9.7.1"

source:
  git_rev: v0.9.7
  git_url: https://github.com/samkos/decimate.git
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools=36.5.0
    - clustershell
    - pandas
  run:
    - python
    - pandas
    - clustershell

test:
  imports:

about:
  home: http://decimate.readthedocs.io
  license: BSD
  license_file: LICENSE.txt
